# base: Node + system tooling for lint/test/build of Angular app
FROM node:24.11.1-alpine3.21 AS base

ENV CHROME_BIN=/usr/bin/chromium-browser \
    PNPM_HOME=/usr/local/share/pnpm \
    PATH="/usr/local/share/pnpm:${PATH}"

RUN apk update && apk add --no-cache \
    libc6-compat \
    git \
    openssh-client \
    nmap \
    chromium && \
    corepack enable pnpm