apiVersion: v1
kind: Pod
metadata:
  name: node-git-chromium-pod
spec:
  containers:
    - name: node-git-chromium
      image: igk19/node-git-chromium:1.0.8
      command:
        - sleep
      args:
        - infinity
      securityContext:
        runAsUser: 1000 # default UID of jenkins user in agent image
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      # workingDir: /home/jenkins
      command:
        - sleep
      args:
        - infinity
      tty: true
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker
  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: kaniko-secret
