apiVersion: v1
kind: Pod
metadata:
    name: node-git-chromium-pod
spec:
    containers:
        - name: node-git-chromium
          image: igk19/node-git-chromium:1.0.9
          automountServiceAccountToken: false
          command:
              - sleep
          args:
              - infinity
          resources:
              requests:
                  memory: '2048Mi'
                  cpu: '600m'
                  ephemeral-storage: '2Gi'
              limits:
                  memory: '2048Mi'
                  cpu: '600m'
                  ephemeral-storage: '2Gi'
          securityContext:
              runAsUser: 1000 # default UID of jenkins user in agent image
        - name: kaniko
          image: gcr.io/kaniko-project/executor:debug
          automountServiceAccountToken: false
          command:
              - sleep
          args:
              - infinity
          tty: true
          resources:
              requests:
                  memory: '1024Mi'
                  cpu: '400m'
                  ephemeral-storage: '500Mi'
              limits:
                  memory: '1024Mi'
                  cpu: '400m'
                  ephemeral-storage: '1Gi'
          volumeMounts:
              - name: jenkins-docker-cfg
                mountPath: /kaniko/.docker
    volumes:
        - name: jenkins-docker-cfg
          projected:
              sources:
                  - secret:
                        name: kaniko-secret
