apiVersion: v1
kind: Pod
metadata:
  name: node-git-chromium-pod
spec:
  containers:
    - image: igk19/node-git-chromium:1.0.8
      name: node-git-chromium
      command:
        - sleep
      args:
        - infinity
